# Generated by Django 4.2.7 on 2023-12-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role_sys', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20, null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'public"."users',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
